### ISSUE TITLE
Edge dot folder notation is breaking plain/text support(?)

### ISSUE THREAD

**Issue by HapLifeMan** [adonisjs/mail#32]
Hi @thetutlage,

I found a problem while using Edge and plain/text mail.

I have this structure:
```
| - views
| --- emails
| ----- edge
| ------- welcome.edge
| ----- plain
| ------- welcome.text
```

This structure is not possible because when sending the mail I use it like this (as described in the documentation, with the `.text` prefix):
```js
await Mails.send(['emails.edge.welcome', 'emails.plain.welcome.text'])
```
The dot-notation folder use the `.text` as a new nested level.
I did it works with `welcome-text.edge` but this is not really beautiful...

I don't know if it is a bug or an expected behaviour...
What is you opinion on this?

Thanks! 🙂

**Comment by thetutlage** [comment]
Yup, a clear bug with the mailer. I will address the issue in the newer release
