### ISSUE TITLE
E_MISSING_CONFIG: ses is not defined

### ISSUE THREAD

**Issue by danielsalles** [adonisjs/mail#37]
I found it difficult to understand how to use SES with this package. I don't know if I'm doing it correctly, because the documentation was not very specific with this driver.

## Package version
`"@adonisjs/mail": "^3.0.9",`

## Node.js and npm version
Node 12

## Sample Code (to reproduce the issue)
.env
`MAIL_CONNECTION=ses`
```js
  await Mail.send(
    'emails.welcome',
    { user: user.toJSON(), tokenQueryString },
     (message) => {
       message
        .to(user.email)
        .from('noreply@')
        .subject('Ative sua conta')
     })
```

**Comment by yasser17** [comment]
I've a similar problem. I added this code to config/mail.js. But not works for me
`
       ses: {
		driver: 'ses',
		accessKeyId: Env.get('SES_KEY'),
		secretAccessKey: Env.get('SES_ACCESS_KEY'),
		region: Env.get('SES_REGION'),
	},
`

E_UNDEFINED_METHOD: Method sendEmail missing on Controller

**Comment by thetutlage** [comment]
I believe the error is not related to the mailer. It says `E_UNDEFINED_METHOD: Method sendEmail missing on Controller`, So controller method is missing

**Comment by thetutlage** [comment]
@danielsalles You need to define the config inside the `config/mail.js` file under the `ses` property.

```js
ses: {
 accessKeyId: '',
 driver: 'ses',
 secretAccessKey: '',
 region: ''
}
```

Config options are same as documented by the AWS https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#constructor-property

**Comment by danielsalles** [comment]
Problem solved. I just think the mail documentation was not very clear. You are changing the doc, is there any branch that I can open a PR? @thetutlage

**Comment by diegobonagurio** [comment]
> @danielsalles You need to define the config inside the `config/mail.js` file under the `ses` property.
> 
> ```js
> ses: {
>  accessKeyId: '',
>  driver: 'ses',
>  secretAccessKey: '',
>  region: ''
> }
> ```
> 
> Config options are same as documented by the AWS https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#constructor-property

after including this in the config / mail.js file, what's the next step to be able to send a test email?

**Comment by iankressin** [comment]
I'm having a hard time trying to send emails using SES too.
Already installed `aws-sdk` on the project and have the following connection configured in my `config/mail.js`
```
module.exports = {
ses: {
    driver: 'ses',
    accessKeyId: Env.get('SES_KEY'),
    secretAccessKey: Env.get('SES_SECRET'),
    region: Env.get('SES_REGION')
  }
};
```
Whenever I try to send any email using :
```
await Mail.send('emails.welcome', 'user.toJSON()', (message) => {
            message
                .to('investimentos.abm@gmail.com')
                .from('ianguimaraes31@gmail.com')
                .subject('Bem vido à abm')
        })
```
I get the error: 
> E_INVALID_PARAMETER: Make sure to define connection inside config/mail.js file > More details: https://err.sh/adonisjs/errors/E_INVALID_PARAMETER

What am I missing?

**Comment by iankressin** [comment]
I'm having a hard time trying to send emails using SES too.
Already installed `aws-sdk` on the project and have the following connection configured in my `config/mail.js`
```
module.exports = {
ses: {
    driver: 'ses',
    accessKeyId: Env.get('SES_KEY'),
    secretAccessKey: Env.get('SES_SECRET'),
    region: Env.get('SES_REGION')
  }
};
```
Whenever I try to send any email using :
```
await Mail.send('emails.welcome', 'user.toJSON()', (message) => {
            message
                .to('myemail@mydomain.com')
                .from('myemail@mydomain.com')
                .subject('Welcome')
        })
```
I get the error: 
> E_INVALID_PARAMETER: Make sure to define connection inside config/mail.js file > More details: https://err.sh/adonisjs/errors/E_INVALID_PARAMETER

What am I missing?
