### ISSUE TITLE
Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by leosalass** [adonisjs/mail#38]
## Package version
addonis 4.1.0

## Node.js and npm version
node v10.16.3
npm 6.9.0

#Mailgun
MAILGUN_DOMAIN="sandboxaXXXXXXXFAKEXXXXXXXXXXX.mailgun.org"
MAILGUN_API_REGION="US"
MAILGUN_API_KEY="XXXXXXXXXXXXXXXXFAKEXXXXXXXXXXXXXXX"

## Sample Code (to reproduce the issue)
`await Mail.raw('<h1> HTML email </h1>', (message) => {
      message.from('foo@bar.com')
      message.to('baz@bar.com')
    })`

## Sample Code 2
`const data = request.only(['email', 'username', 'password'])
    const user = await User.create(data)

    await Mail.send('emails.welcome', user.toJSON(), (message) => {
      message
        .to(user.email)
        .from('<from-email>')
        .subject('Welcome to yardstick')
    })`

## ERROR MESSAGE
`{"error":{"message":"Cannot read property 'body' of undefined","name":"TypeError","status":500,"frames":[{"file":"node_modules\\@adonisjs\\mail\\src\\Request\\index.js","filePath":"E:\\Desarrollos\\WeProtectAll\\code\\wpaccds-rest-api\\node_modules\\@adonisjs\\mail\\src\\Request\\index.js","method":"Request.post","line":98,"column":31,"context":{"start":93,"pre":"        auth: this._basicAuth\n      })\n      return response.body\n    } catch ({ response, message }) {\n      const error = new Error(message)","line":"      error.errors = response.body","post":"      throw error\n    }\n  }\n}\n"},"isModule":true,"isNative":false,"isApp":false},{"file":"internal/process/next_tick.js","filePath":"internal/process/next_tick.js","method":"process._tickCallback","line":68,"column":7,"context":{},"isModule":false,"isNative":true,"isApp":false}]}}`

**Comment by Kordonme** [comment]
I have the same issue. I followed the docs. A template in `resources/views/emails/forgot-password.edge`
and using `await Mail.send('emails.forgot-password')`

**Comment by Kordonme** [comment]
@leosalass 

Just wanted to let you know I figured out the root cause to this exception. In my case the config was wrong. My `MAILGUN_API_REGION` was not  `EU` but instead the EU endpoint `api.eu.mailgun.net`. So basically this boils down to misconfiguration. Check your `.env` for Mailgun related configs.

**Comment by leosalass** [comment]
thanks im goin to test it today. in my config i have US

**Comment by leosalass** [comment]
I did set MAILGUN_API_REGION="api.mailgun.net" but im getting the same error

**Comment by leosalass** [comment]
if it helps this plugin send email with mail gun, but then i dont know how to use adonis views with it, and there is no sense to use it if adonis can user mailgun itself.

https://www.npmjs.com/package/mailgun-js

**Comment by dijsilva** [comment]
I did set in the .env file: 
`MAIL_GUN_REGION=`
I didn't set the value. It worked for me.

**Comment by MrToxy** [comment]
any news on this? getting the same error
