### ISSUE TITLE
Set email header in adonis 4

### ISSUE THREAD

**Issue by stavrogin** [adonisjs/mail#46]
Hi,

I cannot add an email header in config, neither in code.
In Adonis 3.2 it was possible by calling message.header(key, value)
Has this feature been removed or is it possible to do it in another way?

Thanks

**Comment by thetutlage** [comment]
Added back in v5

**Comment by mauricioLopezRamirez** [comment]
hi, how can you add header from version 4.1 of adonis without upgrading to version 5?
