### ISSUE TITLE
No Mail support in adonis v5. 

### ISSUE THREAD

**Issue by prakashbharti786** [adonisjs/mail#50]
## Lack of documentation 
There is no clear documentation for how to set up Mail in Adonis js V5.
Blow the command is not doing anything but updating ace-manifest.json only
```
 node ace invoke @adonisjs/mail  
```

No config file is there for mail as well.

**Comment by RomainLanz** [comment]
Hey @prakashbharti786! 👋 

This provider wasn't ready for AdonisJS V5.
[From `4.1.0`](https://github.com/adonisjs/mail/releases/tag/v4.1.0), you can use it with V5, documentation comes next week.
