### ISSUE TITLE
ses driver issue in @adonisjs/mail:4.1.1

### ISSUE THREAD

**Issue by zulfi007** [adonisjs/mail#52]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

## Node.js and npm version
Node.js version : v14.5.0
Yarn version: 1.22.4

## Sample Code (to reproduce the issue)

**_config_**
   ses: {
      driver: 'ses',
      apiVersion: '2010-12-01',
      key: Env.get('SES_ACCESS_KEY') as string,
      secret: Env.get('SES_ACCESS_SECRET') as string,
      region: Env.get('SES_REGION') as string,
      sslEnabled: true,
      sendingRate: 10,
      maxConnections: 5,
    },

**_error_**
{
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/node_modules/@adonisjs/mail/build/src/Drivers/Ses.js",
        "/node_modules/@adonisjs/mail/build/src/Mail/MailManager.js",
        "/node_modules/@adonisjs/mail/build/providers/MailProvider.js",
        "/node_modules/@poppinss/utils/build/src/esmRequire.js",
        "/node_modules/@poppinss/utils/build/index.js",
        "/node_modules/@adonisjs/core/build/src/Ignitor/Bootstrapper/index.js",
        "/node_modules/@adonisjs/core/build/src/Ignitor/Ace/AppCommands.js",
        "/node_modules/@adonisjs/core/build/src/Ignitor/Ace/index.js",
        "/node_modules/@adonisjs/core/build/src/Ignitor/index.js",
        "/build/server.js"
    ]
}

**Comment by thetutlage** [comment]
Closing, since badly formatted and provides no information.

**Comment by zulfi007** [comment]
> Closing, since badly formatted and provides no information.
Formatted. Please reopen
