### ISSUE TITLE
Dynamic SMTP Server

### ISSUE THREAD

**Issue by TranceGeniK** [adonisjs/mail#55]
Is there a way to set the smtp server (and user/password) at runtime ?

**Comment by thetutlage** [comment]
Which version of the mail package are you using?

**Comment by TranceGeniK** [comment]
3.0.10

**Comment by TranceGeniK** [comment]
Any idea ?

**Comment by thetutlage** [comment]
Hey. Sorry for the late reply. I don't see any direct way to create runtime drivers instances with different config. One way is to register the config at runtime. For example: If you have multiple tenants, then you can use the `tenantId` to register the config like this.

```js
Config.set('mail.tenant1', {
  // config goes here
})
```

And then use it as

```js
Mail.driver('tenant1').send()
```

**Comment by TranceGeniK** [comment]
Thanks, will try !
