### ISSUE TITLE
error when installing @adonisjs/mail

### ISSUE THREAD

**Issue by Alnsentry** [adonisjs/mail#61]
Hi, i want send email with my adonis app, and then i install adonis mail in my app ( adonis install @adonisjs/mail ), 
and then register provider in my start/app.js but when i try to run adonis serve, it throwing error Error: Cannot find module '@adonisjs/mail/providers/MailProvider'.

can some one help me? thank you

## Version
Adonis = 4.1.0
@adonisjs/mail = 7.1.0
npm = 6.11.3
node = 12.10.0

## start/app.js

```
'use strict'

const providers = [
  '@adonisjs/framework/providers/AppProvider',
  '@adonisjs/auth/providers/AuthProvider',
  '@adonisjs/bodyparser/providers/BodyParserProvider',
  '@adonisjs/cors/providers/CorsProvider',
  '@adonisjs/lucid/providers/LucidProvider',
  '@adonisjs/session/providers/SessionProvider',
  '@adonisjs/mail/providers/MailProvider'
]

const aceProviders = [
  '@adonisjs/lucid/providers/MigrationsProvider'
]

const aliases = {}

const commands = []

module.exports = { providers, aceProviders, aliases, commands }

```

**Comment by thetutlage** [comment]
Please check existing issues before creating a new one https://github.com/adonisjs/mail/issues/60#issuecomment-808339684
