### ISSUE TITLE
Edge: "LabeledStatement" is not supported

### ISSUE THREAD

**Issue by AstaDK** [adonisjs/mail#71]
I'm using edge to create template for sending email.
But I faced a error with `Edge`
My code example:
```js
return Mail.send((message) => {
        message
          .embed(Application.tmpPath('/images/bg.png'), 'bg')
          .from('me@gmail.com')
          .to(email)
```
```edge
<div style="background-image: url({{cid:bg}}); padding: 0px 64px 20px 64px ;width: 700px; height: 1200px; margin: 0 auto;  background-repeat: no-repeat; object-fit: contain">
```
then I faced an error:
> status: 'rejected',
  reason: EdgeError: "LabeledStatement" is not supported
 
Have any suggestions for me. Thanks a lot

**Comment by AstaDK** [comment]
@thetutlage Please help me!

**Comment by RomainLanz** [comment]
You have an error in your template.

Closing since you are pinging people to have faster help.
Think about it.

**Comment by thetutlage** [comment]
This should have been a discussion thread at first place. Also, as @RomainLanz stated, please try and avoid pinging people for no reasons.

You are simply referencing `cid` incorrectly. Here's a screenshot from the docs

<img width="764" alt="CleanShot 2021-10-17 at 13 09 24@2x" src="https://user-images.githubusercontent.com/1706381/137616940-dae8415c-8ea8-4bfe-a913-fd3a26b4aee5.png">
