### ISSUE TITLE
Custom headers not sent when using nodemailer

### ISSUE THREAD

**Issue by rmmlopes** [adonisjs/mail#79]
## Package version
7.2.5

## Node.js and npm version
16.14.2
8.5.0

## Sample Code (to reproduce the issue)
Mail headers do not get sent out if this isn't done.  
I'm sure there is a more elegant way of doing this, but this is what got me going
   
/*
 * @adonisjs/mail
 *
 * (c) Harminder Virk <virk@adonisjs.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/// <reference path="../../adonis-typings/mail.ts" />

import nodemailer from 'nodemailer'
import {
  MessageNode,
  SmtpMailResponse,
  SmtpDriverContract,
  SmtpConfig,
} from '@ioc:Adonis/Addons/Mail'

/**
 * Smtp driver to send email using smtp
 */
export class SmtpDriver implements SmtpDriverContract {
  private transporter: any

  constructor(config: SmtpConfig) {
    this.transporter = nodemailer.createTransport(config)
  }

  /**
   * Send message
   */
  public async send(message: MessageNode): Promise<SmtpMailResponse> {
    if (!this.transporter) {
      throw new Error('Driver transport has been closed and cannot be used for sending emails')
    }
    
    message.headers = this.convertHeadersToNodemailFormat(message.headers)
    
    return this.transporter.sendMail(message)
  }

  /**
   * Close transporter connection, helpful when using connections pool
   */
  public async close() {
    this.transporter.close()
    this.transporter = null
  }
  
  /**
   * nodemailer expects an object for headers, Adonis mailer uses an an array of objects
   *   headers: [ { 'x-test': 'teststr' }, { 'x-test': '1234' } ]  ===>
   *   headers: { 'x-test': [ 'teststr', '1234' ] }
   */
  public convertHeadersToNodemailFormat(headers) {
    if (headers) {
      var newHeaders = {}
      for (var header of headers) {
        for (var headerKey in header) {
          if (!newHeaders[headerKey]) {
            newHeaders[headerKey] = []
          }
          if (header[headerKey] instanceof Array) {
            for (var headerListVal of header[headerKey]) {
              newHeaders[headerKey].push(headerListVal)
            }
          } else {
            newHeaders[headerKey].push(header[headerKey])
          }
        }
      }
      return newHeaders
    }
    return headers
  }
}

## BONUS (a sample repo to reproduce the issue)
https://github.com/rmmlopes/mail

**Comment by thetutlage** [comment]
Please format your code properly. Also, the repo you have shared is the fork of the AdonisJS mail package. We need an example app that reproduces the issue.

**Comment by M0nik** [comment]
Same problem.

Nodemailer allow headers in format:
```
...
// allow {key:'content-type', value: 'text/plain'}
...
// allow [{key:'content-type', value: 'text/plain'}]
...
// allow {'content-type': 'text/plain'}
...
```
[addHeader(key, value)](https://github.com/nodemailer/nodemailer/blob/master/lib/mime-node/index.js#L321)

But [here](https://github.com/adonisjs/mail/blob/develop/src/Message/index.ts#L269), we create array of objects like **[{'content-type': 'text/plain'}]** 

Nodemailer requires **[{key: 'content-type', value: 'text/plain'}]**

**Comment by thetutlage** [comment]
It has been fixed in this commit. But will be part of the upcoming major release.

https://github.com/adonisjs/mail/commit/9da5f16e91b1e6800891b53ab6568ef2d3dad403#diff-60ea006d358dc5cddec873646d6aaae8ee58e5dcee845e71069a25b99ba126bbR265-R271
