### ISSUE TITLE
Can't send email to multiple recipients.

### ISSUE THREAD

**Issue by bestmbed** [adonisjs/mail#88]
## Can't send email to multiple recipients.

I tried to send email to multiple recipients by using `Mail.sendLater` But i got an error like below picture.
![Screenshot 2566-06-16 at 10 59 51](https://github.com/adonisjs/mail/assets/39818219/71c13f3d-b562-40eb-812d-4c31ad9d858f)

Could you please help me to solve this issue.

Thank you.

## Package version
- "@adonisjs/mail": "^8.1.2" 

## Node.js and npm version
- node --version v20.0.0 
- pnpm -v  8.6.2

## Sample Code (to reproduce the issue)
```
const mails :string = 'best@example.com, test2@example.com'      
await Mail.sendLater((message) => {
          message
            .from('wareboxtech.service@gmail.com')
            .to(mails)
            .subject(`${data.type}`)
            .htmlView('emails/template', {
              alarm: data.type,
              site_name: data.site_name,
              device_no: data.device_id,
              timestamp: moment().format('DD MM YYYY hh:mm:ss'),
            })
          })
```

**Comment by Julien-R44** [comment]
https://docs.adonisjs.com/guides/mailer#to
